package:
  format-version: "1.0.0"
  name: "touch"
  version: "3.14.0"
  type: "api"
  status: "production"
  
  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"
    - name: "harmony-services"
      type: "package"
      version: "v1.3.1"
